#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#case $GPU_MODE in
#    nvidia)
#        case $NVIDIA_MODE in
#            hybrid)
#                xrandr --setprovideroutputsource NVIDIA-G0 modesetting
#                ;;
#            nvidia)
#                xrandr --setprovideroutputsource modesetting NVIDIA-0
#                ;;
 #       esac
 #       xrandr --auto
 #       ;;
 #   integrated)
 #       echo "lel this is mostly useless"
 #       ;;
#esac
i3
sudo /usr/bin/prime-switch
clear

